package harness

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"regexp"
	"strings"
	"time"
)

// EvidenceKind identifies the shape of audit evidence collected.
type EvidenceKind string

const (
	EvidenceKindCommandExecution EvidenceKind = "command_execution"
	EvidenceKindFileMutation     EvidenceKind = "file_mutation"
	EvidenceKindPolicyDecision   EvidenceKind = "policy_decision"
	EvidenceKindSandboxAudit     EvidenceKind = "sandbox_audit"
	EvidenceKindAdapterHealth    EvidenceKind = "adapter_health"
	EvidenceKindEngineDiagnostic EvidenceKind = "engine_diagnostic"
)

// EvidenceRecord is the typed, immutable audit evidence item generated by tool execution.
// It is UNTRUSTED EVIDENCE; Inspector evaluates it before Orchestra marks success.
type EvidenceRecord struct {
	ID              string          `json:"id"`
	ContractVersion string          `json:"contractVersion"`
	ExecutionID     string          `json:"executionId"`
	TaskID          string          `json:"taskId"`
	WorktreeID      string          `json:"worktreeId"`
	Kind            EvidenceKind    `json:"kind"`
	Digest          string          `json:"digest"`
	RedactedPayload json.RawMessage `json:"redactedPayload"`
	Audit           AuditMetadata   `json:"audit,omitempty"`
	CollectedAt     time.Time       `json:"collectedAt"`
	SchemaVersion   string          `json:"schemaVersion"`
}

// ComputeDigest computes a SHA-256 fingerprint for arbitrary bytes.
func ComputeDigest(data []byte) string {
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:])
}

// NewEvidenceRecord builds a sanitized evidence record with a cryptographic digest.
func NewEvidenceRecord(executionID, taskID, worktreeID string, kind EvidenceKind, payload any) (EvidenceRecord, error) {
	if executionID == "" || taskID == "" || worktreeID == "" {
		return EvidenceRecord{}, fmt.Errorf("%w: execution, task, and worktree IDs are required", ErrInvalidContract)
	}
	raw, err := json.Marshal(payload)
	if err != nil {
		return EvidenceRecord{}, fmt.Errorf("%w: marshaling evidence payload: %v", ErrInvalidContract, err)
	}
	redacted := RedactBytes(raw)
	digest := ComputeDigest(redacted)
	id := fmt.Sprintf("ev_%s_%s", kind, digest[:12])

	return EvidenceRecord{
		ID:              id,
		ContractVersion: HarnessContractVersion,
		ExecutionID:     executionID,
		TaskID:          taskID,
		WorktreeID:      worktreeID,
		Kind:            kind,
		Digest:          digest,
		RedactedPayload: redacted,
		Audit: AuditMetadata{
			TraceID: executionID,
		},
		CollectedAt:   time.Now().UTC(),
		SchemaVersion: HarnessContractVersion,
	}, nil
}

// Redactor handles string sanitization to avoid leaking credentials, absolute paths, or tokens.
type Redactor interface {
	Redact(s string) string
	RedactBytes(b []byte) []byte
}

var (
	kvSecretPattern    = regexp.MustCompile(`(?i)("?(?:api[_-]?key|secret|token|password|passwd|auth|bearer)"?[\s:=]+["']?)([a-zA-Z0-9_\-\.]{8,})(["']?)`)
	ghpTokenPattern    = regexp.MustCompile(`(?i)(ghp_[a-zA-Z0-9]{20,}|github_pat_[a-zA-Z0-9]{20,})`)
	skTokenPattern     = regexp.MustCompile(`(?i)sk-[a-zA-Z0-9]{20,}`)
	urlCredPattern     = regexp.MustCompile(`(?i)[a-zA-Z0-9_-]+:[a-zA-Z0-9_-]+@`)
	windowsRootPattern = regexp.MustCompile(`(?i)[a-zA-Z]:\\[^\s"']+`)
	unixRootPattern    = regexp.MustCompile(`(?:/(?:home|Users|tmp|var|etc|usr|opt|root)/[^\s"']+)`)
)

// RedactString removes secrets and normalizes backslashes from a string.
func RedactString(s string) string {
	res := s
	// Redact key-value secrets while preserving delimiters and JSON string quotes
	res = kvSecretPattern.ReplaceAllString(res, "${1}[REDACTED]${3}")
	// Redact standalone tokens and credentials
	res = ghpTokenPattern.ReplaceAllString(res, "[REDACTED]")
	res = skTokenPattern.ReplaceAllString(res, "[REDACTED]")
	res = urlCredPattern.ReplaceAllString(res, "[REDACTED]@")

	// Neutralize absolute Windows drive letters to avoid host path leakage
	res = windowsRootPattern.ReplaceAllStringFunc(res, func(match string) string {
		parts := strings.Split(strings.ReplaceAll(match, `\`, "/"), "/")
		if len(parts) > 0 {
			return ".../" + parts[len(parts)-1]
		}
		return "[PATH]"
	})
	// Neutralize absolute Unix paths to avoid host path leakage
	res = unixRootPattern.ReplaceAllStringFunc(res, func(match string) string {
		parts := strings.Split(match, "/")
		if len(parts) > 0 {
			return ".../" + parts[len(parts)-1]
		}
		return "[PATH]"
	})
	return res
}

// RedactBytes performs JSON-safe redaction.
func RedactBytes(b []byte) []byte {
	return []byte(RedactString(string(b)))
}
